name: A R E N A
title: MIDNIGHT ARENA | Enter the Forbidden World of Gaming
description: Midnight Arina is a blog dedicated to the darker side of gaming, where boundaries blur, and desires come to life. Step into a world where only the bold survive.
tags:
  - blog
  - adult gaming
  - gaming community
  - gaming news
  - nudes
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
